"""Document parsing and chunking.

Chunking decides what the retriever can possibly find, so it is treated as a
first-class design step rather than a one-line text split.

Strategy: **structure-aware chunking.** Documents are split on markdown
section headings first, and only oversized sections are split further by
character window. Every chunk is prefixed with its document title and section
heading, so an isolated chunk still carries enough context for both the
embedding model and the LLM reading the citation.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

# Chunk sizing. bge-small has a 512-token window; ~1,200 characters keeps a
# chunk comfortably inside it while staying large enough to hold a whole
# "Root Cause" or "Remediation" section.
MAX_CHUNK_CHARS = 1_200
CHUNK_OVERLAP_CHARS = 150
MIN_CHUNK_CHARS = 80

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
_SECTION_RE = re.compile(r"^##\s+(.+)$", re.MULTILINE)


@dataclass
class DocumentMeta:
    """Frontmatter of a knowledge-base document."""

    doc_id: str
    title: str
    department: str
    document_type: str
    access_level: str
    created_date: str
    tags: list[str] = field(default_factory=list)

    @property
    def created_timestamp(self) -> int:
        """Unix day number, so Pinecone can run numeric range filters.

        Pinecone metadata filters support ``$gte``/``$lte`` on numbers but not
        on date strings, and the RLM demo question filters by "the last year" -
        so a sortable numeric form is stored alongside the readable date.
        """
        y, m, d = (int(part) for part in self.created_date.split("-"))
        return date(y, m, d).toordinal()


@dataclass
class Chunk:
    """One embeddable unit of text plus everything needed to cite it."""

    chunk_id: str
    text: str
    section: str
    chunk_index: int
    meta: DocumentMeta

    def to_metadata(self) -> dict[str, object]:
        """Flat metadata payload stored next to the vector.

        The raw text is stored too: retrieval must return quotable evidence,
        and a second round trip to disk to fetch it would be wasteful.
        """
        return {
            "doc_id": self.meta.doc_id,
            "title": self.meta.title,
            "department": self.meta.department,
            "document_type": self.meta.document_type,
            "access_level": self.meta.access_level,
            "created_date": self.meta.created_date,
            "created_ts": self.meta.created_timestamp,
            "tags": self.meta.tags,
            "section": self.section,
            "chunk_index": self.chunk_index,
            "text": self.text,
        }


def _parse_scalar(raw: str) -> str:
    """Strip surrounding quotes from a frontmatter scalar."""
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        return raw[1:-1]
    return raw


def parse_frontmatter(content: str) -> tuple[DocumentMeta, str]:
    """Split a markdown document into its frontmatter and its body.

    A tiny purpose-built parser is used instead of a YAML dependency: the
    frontmatter shape is fixed and generated by this project, so the full YAML
    surface (and its known injection foot-guns) is not needed.

    Raises:
        ValueError: if the document has no frontmatter block.
    """
    match = _FRONTMATTER_RE.match(content)
    if not match:
        raise ValueError("document has no frontmatter block")

    fields: dict[str, object] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, raw = line.split(":", 1)
        key, raw = key.strip(), raw.strip()
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            fields[key] = [_parse_scalar(p) for p in inner.split(",") if p.strip()] if inner else []
        else:
            fields[key] = _parse_scalar(raw)

    meta = DocumentMeta(
        doc_id=str(fields.get("doc_id", "")),
        title=str(fields.get("title", "")),
        department=str(fields.get("department", "unknown")),
        document_type=str(fields.get("document_type", "unknown")),
        access_level=str(fields.get("access_level", "internal")),
        created_date=str(fields.get("created_date", "1970-01-01")),
        tags=list(fields.get("tags", [])),  # type: ignore[arg-type]
    )
    return meta, content[match.end():]


def _split_sections(body: str) -> list[tuple[str, str]]:
    """Split a markdown body into ``(section_heading, section_text)`` pairs."""
    matches = list(_SECTION_RE.finditer(body))
    if not matches:
        return [("Document", body.strip())]

    sections: list[tuple[str, str]] = []
    preamble = body[: matches[0].start()].strip()
    if len(preamble) >= MIN_CHUNK_CHARS:
        sections.append(("Overview", preamble))

    for i, match in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        text = body[match.end():end].strip()
        if text:
            sections.append((match.group(1).strip(), text))
    return sections


def _window(text: str) -> list[str]:
    """Split an oversized section into overlapping character windows.

    Overlap exists so a sentence spanning a boundary is still fully present in
    at least one chunk.
    """
    if len(text) <= MAX_CHUNK_CHARS:
        return [text]

    parts: list[str] = []
    start = 0
    while start < len(text):
        end = min(start + MAX_CHUNK_CHARS, len(text))
        if end < len(text):
            # Prefer to break at a paragraph, then a sentence, then anywhere.
            for marker in ("\n\n", ". ", "\n"):
                cut = text.rfind(marker, start + MIN_CHUNK_CHARS, end)
                if cut != -1:
                    end = cut + len(marker)
                    break
        parts.append(text[start:end].strip())
        if end >= len(text):
            break
        start = max(end - CHUNK_OVERLAP_CHARS, start + 1)
    return [p for p in parts if len(p) >= MIN_CHUNK_CHARS]


def chunk_document(content: str) -> list[Chunk]:
    """Turn one markdown document into retrievable chunks."""
    meta, body = parse_frontmatter(content)
    chunks: list[Chunk] = []

    for section, section_text in _split_sections(body):
        for part in _window(section_text):
            index = len(chunks)
            # Context prefix: an isolated chunk still says what it belongs to.
            contextual = f"{meta.title}\n## {section}\n\n{part}"
            chunks.append(
                Chunk(
                    chunk_id=f"{meta.doc_id}::{index}",
                    text=contextual,
                    section=section,
                    chunk_index=index,
                    meta=meta,
                )
            )
    return chunks


def load_corpus(directory: Path) -> list[Chunk]:
    """Load and chunk every markdown document in a directory."""
    chunks: list[Chunk] = []
    for path in sorted(directory.glob("*.md")):
        try:
            chunks.extend(chunk_document(path.read_text(encoding="utf-8")))
        except ValueError as exc:
            raise ValueError(f"{path.name}: {exc}") from exc
    return chunks
